#!/usr/bin/env python

import wandb
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("run_id", default="last")
args = parser.parse_args()
run_id = args.run_id

api = wandb.Api()
if run_id == "last":
    run = api.runs(path="krshna/isaacgymenvs", per_page=1)[0]
else:
    run = api.run("krshna/isaacgymenvs/{run_id}")
print(f"deleting run id: {run.id}")
run.delete()
