hand_dist:
  reward_fn_partial: 
    _partial_: true
    _target_: isaacgymenvs.utils.rewards.hand_dist
  args: 
    - object_pos
    - hand_palm_pos
    - fingertip_pos
<<<<<<< HEAD
  scale: -10.0
=======
  scale: -0.75
>>>>>>> internal/2024_01_25_dispensers
