manipulability_reward:
  reward_fn_partial: 
    _partial_: true
    _target_: isaacgymenvs.utils.rewards.manipulability_frobenius_norm
  args:
    - manipulability
    # - object_pose
    # - goal_pose
  scale: 1
