hydra:
  run:
    dir: .
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    root:
      level: ERROR
    disable_existing_loggers: true
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: null
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - task=ManipulabilityVectorizedArticulateTaskSpray1
    - train=AllegroHandGraspPPO
    - experiment=ManipulabilityVectorizedArticulateTaskSpray1
    - task.rewards.hand_dist.scale=-50.
    - wandb_activate=true
    - headless=True
    - num_envs=8192
    - train.params.config.max_epochs=750
  job:
    name: train
    chdir: null
    override_dirname: experiment=ManipulabilityVectorizedArticulateTaskSpray1,headless=True,num_envs=8192,task.rewards.hand_dist.scale=-50.,task=ManipulabilityVectorizedArticulateTaskSpray1,train.params.config.max_epochs=750,train=AllegroHandGraspPPO,wandb_activate=true
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.1'
    cwd: /home/jcollins90/IsaacGymEnvs/isaacgymenvs
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /home/jcollins90/IsaacGymEnvs/isaacgymenvs/cfg
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      train: AllegroHandGraspPPO
      task: ManipulabilityVectorizedArticulateTaskSpray1
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: disabled
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
task:
  name: ArticulateTask
  physics_engine: ${..physics_engine}
  env:
    numEnvs: ${resolve_default:16384,${...num_envs}}
    numActions: 22
    envSpacing: 0.75
    episodeLength: 600
    enableDebugVis: false
    aggregateMode: 1
    clipObservations: 5.0
    clipActions: 1.0
    stiffnessScale: 1.0
    forceLimitScale: 1.0
    useRelativeControl: false
    dofSpeedScale: 20.0
    actionsMovingAverage: 1.0
    controlFrequencyInv: 2
    startPositionNoise: 0.01
    startRotationNoise: 0.0
    resetPositionNoise: 0.01
    resetRotationNoise: 0.0
    resetDofPosRandomInterval: 0.2
    resetDofVelRandomInterval: 0.0
    forceScale: 0.0
    forceProbRange:
    - 0.001
    - 0.1
    forceDecay: 0.99
    forceDecayInterval: 0.08
    successTolerance: 0.005
    rewardParams:
      task_rew: ${task.rewards.task_reward}
      hand_dist: ${task.rewards.hand_dist}
      action_penalty: ${task.rewards.action_penalty}
      reach_bonus: ${task.rewards.reach_bonus}
      fall_penalty: ${task.rewards.drop_penalty}
      hand_rot_reward: ${task.rewards.hand_rot_reward}
      manipulability_reward_vectorized: ${task.rewards.manipulability_reward_vectorized}
    fallPenalty: 0.0
    objectType:
    - spray_bottle
    objectInstance:
      spray_bottle:
      - 0
    objectDofName: joint_0
    objectDofTargetPos:
    - 0.075
    scaleDofPos: false
    objectMassBaseOnly: true
    objectMass: 10
    objectStiffness: 3
    objectDamping: 0.1
    fixObjectBase: false
    observationType: full_state
    asymmetric_observations: false
    printNumSuccesses: false
    maxConsecutiveSuccesses: 100
    asset:
      assetFileName: urdf/kuka_allegro_description/allegro_grasp.urdf
      assetFileNameBlock: urdf/objects/cube_multicolor_allegro.urdf
      assetFileNameEgg: mjcf/open_ai_assets/hand/egg.xml
      assetFileNamePen: mjcf/open_ai_assets/hand/pen.xml
      assetFileNameBottle: urdf/objects/bottle/mobility.urdf
      assetFileNamePillBottle: urdf/objects/pill_bottle/mobility.urdf
      assetFileNameSprayBottle:
      - urdf/objects/spray_bottle/mobility.urdf
      - urdf/objects/spray_bottle2/mobility.urdf
      assetFileNameDispenser: urdf/objects/dispenser/mobility.urdf
  task:
    randomize: false
    randomization_params:
      frequency: 720
      observations:
        range:
        - 0
        - 0.002
        range_correlated:
        - 0
        - 0.001
        operation: additive
        distribution: gaussian
      actions:
        range:
        - 0.0
        - 0.05
        range_correlated:
        - 0
        - 0.015
        operation: additive
        distribution: gaussian
      sim_params:
        gravity:
          range:
          - 0
          - 0.4
          operation: additive
          distribution: gaussian
      actor_params:
        hand:
          color: true
          dof_properties:
            damping:
              range:
              - 0.3
              - 3.0
              operation: scaling
              distribution: loguniform
            stiffness:
              range:
              - 0.75
              - 1.5
              operation: scaling
              distribution: loguniform
            lower:
              range:
              - 0
              - 0.01
              operation: additive
              distribution: gaussian
            upper:
              range:
              - 0
              - 0.01
              operation: additive
              distribution: gaussian
          rigid_body_properties:
            mass:
              range:
              - 0.5
              - 1.5
              operation: scaling
              distribution: uniform
              setup_only: true
          rigid_shape_properties:
            friction:
              num_buckets: 250
              range:
              - 0.7
              - 1.3
              operation: scaling
              distribution: uniform
        object:
          scale:
            range:
            - 0.95
            - 1.05
            operation: scaling
            distribution: uniform
            setup_only: true
          rigid_body_properties:
            mass:
              range:
              - 0.5
              - 1.5
              operation: scaling
              distribution: uniform
              setup_only: true
          rigid_shape_properties:
            friction:
              num_buckets: 250
              range:
              - 0.7
              - 1.3
              operation: scaling
              distribution: uniform
    enableCameraSensors: false
  sim:
    dt: 0.01667
    substeps: 2
    up_axis: z
    use_gpu_pipeline: ${eq:${...pipeline},"gpu"}
    gravity:
    - 0.0
    - 0.0
    - -9.81
    physx:
      num_threads: ${....num_threads}
      solver_type: ${....solver_type}
      use_gpu: ${contains:"cuda",${....sim_device}}
      num_position_iterations: 8
      num_velocity_iterations: 0
      max_gpu_contact_pairs: 8388608
      num_subscenes: ${....num_subscenes}
      contact_offset: 0.002
      rest_offset: 0.0
      bounce_threshold_velocity: 0.2
      max_depenetration_velocity: 1000.0
      default_buffer_size_multiplier: 5.0
      contact_collection: 0
  rewards:
    action_penalty:
      reward_fn_partial:
        _partial_: true
        _target_: isaacgymenvs.utils.rewards.action_penalty
      args:
      - actions
      scale: -0.0002
    object_pos_err:
      reward_fn_partial:
        _partial_: true
        _target_: isaacgymenvs.utils.rewards.l2_dist
      args:
      - target_pos
      - object_pos
      scale: -10.0
    object_dof_pos_err:
      reward_fn_partial:
        _partial_: true
        _target_: isaacgymenvs.utils.rewards.l2_dist
      args:
      - object_dof_pos
      - goal_dof_pos
      scale: -10.0
    task_reward:
      reward_fn_partial:
        _partial_: true
        _target_: isaacgymenvs.utils.rewards.l2_dist_exp_normalized
      args:
      - object_dof_pos
      - goal_dof_pos
      scale: 1
    reach_bonus:
      reward_fn_partial:
        _partial_: true
        _target_: isaacgymenvs.utils.rewards.reach_bonus
      args:
      - object_dof_pos
      - goal_dof_pos
      - success_tolerance
      scale: 250.0
    drop_penalty:
      reward_fn_partial:
        _partial_: true
        _target_: isaacgymenvs.utils.rewards.drop_penalty
      args:
      - object_pos
      - goal_pos
      - 0.24
      scale: -50.0
    hand_dist:
      reward_fn_partial:
        _partial_: true
        _target_: isaacgymenvs.utils.rewards.hand_dist
      args:
      - object_pos
      - hand_palm_pos
      - fingertip_pos
      scale: -50.0
    hand_rot_reward:
      reward_fn_partial:
        _partial_: true
        _target_: isaacgymenvs.utils.rewards.rot_reward
      args:
      - hand_quat
      - hand_init_quat
      scale: 0.1
    manipulability_reward_vectorized:
      reward_fn_partial:
        _partial_: true
        _target_: isaacgymenvs.utils.rewards.manipulability_frobenius_norm_vectorized
      args:
      - manipulability
      - object_pose
      - goal_pose
      - actions
      scale: 1
train:
  params:
    seed: ${...seed}
    algo:
      name: a2c_continuous
    model:
      name: continuous_a2c_logstd
    network:
      name: actor_critic
      separate: false
      space:
        continuous:
          mu_activation: None
          sigma_activation: None
          mu_init:
            name: default
          sigma_init:
            name: const_initializer
            val: 0
          fixed_sigma: true
      mlp:
        units:
        - 512
        - 256
        - 128
        activation: elu
        d2rl: false
        initializer:
          name: default
        regularizer:
          name: None
    load_checkpoint: ${if:${...checkpoint},True,False}
    load_path: ${...checkpoint}
    config:
      name: ${resolve_default:AllegroHandGrasp,${....experiment}}
      full_experiment_name: ${.name}
      env_name: rlgpu
      multi_gpu: false
      ppo: true
      mixed_precision: false
      normalize_input: true
      normalize_value: true
      value_bootstrap: true
      num_actors: ${....task.env.numEnvs}
      reward_shaper:
        scale_value: 0.01
      normalize_advantage: true
      gamma: 0.99
      tau: 0.95
      learning_rate: 0.005
      lr_schedule: adaptive
      schedule_type: standard
      kl_threshold: 0.02
      score_to_win: 100000
      max_epochs: 750
      save_best_after: 500
      save_frequency: 200
      print_stats: true
      grad_norm: 1.0
      entropy_coef: 0.0
      truncate_grads: true
      e_clip: 0.2
      horizon_length: 8
      minibatch_size: ${eval:${....task.env.numEnvs}*2}
      mini_epochs: 5
      critic_coef: 4
      clip_value: true
      seq_len: 4
      bounds_loss_coef: 0.0001
      score_keys:
      - goal_dist
      - hand_dist
      - task_dist
      player:
        deterministic: true
        games_num: 100000
        print_stats: true
        device: ${rl_device}
task_name: ${task.name}
experiment: ManipulabilityVectorizedArticulateTaskSpray1
num_envs: 8192
seed: 42
torch_deterministic: false
max_iterations: ''
physics_engine: physx
pipeline: gpu
sim_device: cuda:0
rl_device: cuda:0
graphics_device_id: 0
num_threads: 4
solver_type: 1
num_subscenes: 4
test: false
checkpoint: ''
sigma: ''
multi_gpu: false
wandb_activate: true
wandb_group: ''
wandb_name: ${train.params.config.name}
wandb_entity: ''
wandb_project: manipulability-isaacgym
wandb_tags: []
wandb_logcode_dir: ''
capture_video: false
capture_video_freq: 1464
capture_video_len: 100
force_render: true
headless: true
